/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package component.fields;

import component.IGetValue;
import java.awt.Component;
import javax.swing.JPanel;

public abstract class AbstractPanelInput extends JPanel implements IGetValue {

    private String nameOfPanel;

    public AbstractPanelInput(String lbName) {
        this.nameOfPanel= getNameOfPanel();
        abstractInitComponents();
        initComponents();
        setDefaultValues(lbName);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbName = new javax.swing.JLabel();
        lbError = new javax.swing.JLabel();

        setLayout(null);

        lbName.setText("jLabel1");
        add(lbName);
        lbName.setBounds(10, 10, 110, 20);

        lbError.setForeground(java.awt.Color.red);
        lbError.setText("jLabel1");
        add(lbError);
        lbError.setBounds(10, 50, 380, 30);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lbError;
    private javax.swing.JLabel lbName;
    // End of variables declaration//GEN-END:variables

    private void setDefaultValues(String lbName) {
        this.lbName.setText(lbName);
        lbError.setText("");
        Component panel = getPanel();
        panel.setBounds(150, 10, 240, 30);
        add(panel);
    }

    protected abstract void abstractInitComponents();

    protected abstract Component getPanel();
    
    protected abstract String getNameOfPanel();

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null || (getClass() != obj.getClass())) {
            return false;
        }

        AbstractPanelInput api= (AbstractPanelInput) obj;
        
        return this.nameOfPanel == api.nameOfPanel;
    }

    

}
