/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import abstractFactory.AbstractFactory;
import component.fields.AbstractPanelInput;
import abstractFactory.impl.*;
import builder.Builder;
import builder.impl.*;
import factoryMethod.Creator;
import factoryMethod.impl.*;

public class FrmMain extends javax.swing.JFrame {

    public FrmMain() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroup1 = new javax.swing.ButtonGroup();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuBarConfiguration = new javax.swing.JMenuBar();
        menuConfig = new javax.swing.JMenu();
        menuItemForm1 = new javax.swing.JMenuItem();
        menuItemForm2 = new javax.swing.JMenuItem();
        menuItemForm3 = new javax.swing.JMenuItem();
        menuItemCustom = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuConfig.setText("Configuration");

        menuItemForm1.setText("Form-1");
        menuItemForm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemForm1ActionPerformed(evt);
            }
        });
        menuConfig.add(menuItemForm1);

        menuItemForm2.setText("Form-2");
        menuItemForm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemForm2ActionPerformed(evt);
            }
        });
        menuConfig.add(menuItemForm2);

        menuItemForm3.setText("Form-3");
        menuItemForm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemForm3ActionPerformed(evt);
            }
        });
        menuConfig.add(menuItemForm3);

        menuItemCustom.setText("Customize");
        menuItemCustom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCustomActionPerformed(evt);
            }
        });
        menuConfig.add(menuItemCustom);

        menuBarConfiguration.add(menuConfig);

        setJMenuBar(menuBarConfiguration);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemForm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemForm1ActionPerformed
        initializeFrmPerson(new ConcreteFactory1());
//        initializeFrmPerson(new ConcreteBuilder1());
//        initializeFrmPerson(new ConcreteFactory1());
    }//GEN-LAST:event_menuItemForm1ActionPerformed

    private void menuItemForm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemForm2ActionPerformed
        initializeFrmPerson(new ConcreteFactory2());
//        initializeFrmPerson(new ConcreteBuilder2());
//        initializeFrmPerson(new ConcreteCreator2());
    }//GEN-LAST:event_menuItemForm2ActionPerformed

    private void menuItemForm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemForm3ActionPerformed
        initializeFrmPerson(new ConcreteFactory3());
//        initializeFrmPerson(new ConcreteBuilder3());
//        initializeFrmPerson(new ConcreteCreator3());
    }//GEN-LAST:event_menuItemForm3ActionPerformed

    private void menuItemCustomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCustomActionPerformed
        FrmCustom frmCustom = new FrmCustom();
        frmCustom.setVisible(true);
        frmCustom.setTitle("Izaberite zeljeni izgled komponenti forme");
        
    }//GEN-LAST:event_menuItemCustomActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btnGroup1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuBar menuBarConfiguration;
    private javax.swing.JMenu menuConfig;
    private javax.swing.JMenuItem menuItemCustom;
    private javax.swing.JMenuItem menuItemForm1;
    private javax.swing.JMenuItem menuItemForm2;
    private javax.swing.JMenuItem menuItemForm3;
    // End of variables declaration//GEN-END:variables

    private void initializeFrmPerson(AbstractFactory factory) {
        AbstractPanelInput panelFirstName = factory.createPanelInputFirstName();
        AbstractPanelInput panelLastName = factory.createPanelInputLastName();
        AbstractPanelInput panelGender = factory.createPanelInputGender();
        AbstractPanelInput panelDate = factory.createPanelInputDate();
        
        FrmPerson frmPerson = new FrmPerson(panelFirstName, panelLastName, panelGender, panelDate);
        frmPerson.setVisible(true);
    }

    private void initializeFrmPerson(Builder builder) {
        builder.createPanelInputFirstName();
        builder.createPanelInputLastName();
        builder.createPanelInputGender();
        builder.createPanelInputDate();
        
        FrmPerson frmPerson = builder.buildForm();
        frmPerson.setVisible(true);
    }

    private void initializeFrmPerson(Creator creator) {
        FrmPerson frmPerson = creator.createForm();
        frmPerson.setVisible(true);
    }
}
