/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import component.fields.AbstractPanelInput;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JOptionPane;


public class FrmPerson extends JDialog {

    private final AbstractPanelInput panelFirstName;
    private final AbstractPanelInput panelLastName;
    private final AbstractPanelInput panelGender;
    private final AbstractPanelInput panelDate;
    
    private JButton btnSave;

    
    public FrmPerson(AbstractPanelInput panelFirstName, AbstractPanelInput panelLastName, AbstractPanelInput panelGender, AbstractPanelInput panelDate) {
        
        this.panelFirstName = panelFirstName;
        this.panelLastName = panelLastName;
        this.panelGender = panelGender;
        this.panelDate = panelDate;
        initComponents();
        prepareView();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridLayout(5, 1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    private void prepareView() {
        btnSave = new javax.swing.JButton("Save");
        btnSave.addActionListener(new btnSaveListener(this));

        getContentPane().add(panelFirstName);
        getContentPane().add(panelLastName);
        getContentPane().add(panelGender);
        getContentPane().add(panelDate);
        getContentPane().add(btnSave);

        getContentPane().setPreferredSize(new Dimension(400,500));
        pack();
        setLocationRelativeTo(null);
    }

    private class btnSaveListener implements ActionListener {

        private final FrmPerson frmPerson;

        public btnSaveListener(FrmPerson frmPerson) {
            this.frmPerson = frmPerson;
        }

        @Override
        public void actionPerformed(ActionEvent e) {

            String firstName = (String) panelFirstName.getValue();
            String lastName = (String) panelLastName.getValue();
            String gender = (String) panelGender.getValue();
            String date = panelDate.getValue().toString();
  
            JOptionPane.showMessageDialog(frmPerson, "Ime: "+firstName+" Prezime: "+lastName+" Pol: "+gender+" Datum rodjenja:"+date, "Kreirana je nova osoba", JOptionPane.INFORMATION_MESSAGE);
        }

    }

}
